"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 16:40:44.662220
"""
import sqlalchemy as sa

from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('audit_log',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('ts', sa.String(length=30), nullable=False),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_name', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_target'), ['target'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('detectors',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('run_period', sa.String(length=7), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('format', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('share_token', sa.String(length=40), nullable=False),
    sa.Column('share_expires_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_run_id'), ['run_id'], unique=False)

    op.create_table('rule_versions',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('rule_id', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.String(length=120), nullable=False),
    sa.Column('changed_at', sa.String(length=30), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_versions_rule_id'), ['rule_id'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('scope_value', sa.String(length=200), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.JSON(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered', sa.String(length=30), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('proposed_rule_id', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accounts', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('file_ids', sa.JSON(), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('ai_usage', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('format', sa.String(length=4), nullable=False),
    sa.Column('detected', sa.String(length=30), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('txn_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_txn_ids', sa.JSON(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('routing', sa.String(length=20), nullable=False),
    sa.Column('routing_reason', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prev_status', sa.String(length=20), nullable=True),
    sa.Column('agent_trace', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('assignee', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('human_category', sa.String(length=20), nullable=True),
    sa.Column('false_positive', sa.Boolean(), nullable=True),
    sa.Column('covered_txn_ids', sa.JSON(), nullable=False),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)

    op.create_table('match_pairs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('bank_txn_ids', sa.JSON(), nullable=False),
    sa.Column('ledger_txn_ids', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('pass_name', sa.String(length=40), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_pairs_run_id'), ['run_id'], unique=False)

    op.create_table('proposed_rules',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('supporting_txn_ids', sa.JSON(), nullable=False),
    sa.Column('simulation', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposed_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposed_rules_run_id'), ['run_id'], unique=False)

    op.create_table('run_events',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_events_run_id'), ['run_id'], unique=False)

    op.create_table('txns',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.String(length=24), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('vendor_norm', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('account_id', sa.String(length=40), nullable=False),
    sa.Column('gl_code', sa.String(length=80), nullable=True),
    sa.Column('source_file', sa.String(length=200), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('raw_row', sa.JSON(), nullable=False),
    sa.Column('external', sa.Boolean(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk')
    )
    with op.batch_alter_table('txns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_txns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_txns_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_txns_run_txn', ['run_id', 'id'], unique=True)
        batch_op.create_index(batch_op.f('ix_txns_vendor_norm'), ['vendor_norm'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('finding_id', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('mentions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_finding_id'), ['finding_id'], unique=False)

    # ### end Alembic commands ###

    # Append-only audit log: block UPDATE/DELETE at the database level.
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        for verb in ("UPDATE", "DELETE"):
            op.execute(f"CREATE TRIGGER IF NOT EXISTS audit_no_{verb.lower()} BEFORE {verb} ON audit_log "
                       "BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END;")
    elif bind.dialect.name == "postgresql":
        op.execute("""CREATE OR REPLACE FUNCTION audit_log_append_only() RETURNS trigger AS $$
            BEGIN RAISE EXCEPTION 'audit_log is append-only'; END; $$ LANGUAGE plpgsql;""")
        op.execute("CREATE TRIGGER audit_log_no_mutation BEFORE UPDATE OR DELETE ON audit_log "
                   "FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_finding_id'))

    op.drop_table('comments')
    with op.batch_alter_table('txns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_txns_vendor_norm'))
        batch_op.drop_index('ix_txns_run_txn')
        batch_op.drop_index(batch_op.f('ix_txns_run_id'))
        batch_op.drop_index(batch_op.f('ix_txns_id'))

    op.drop_table('txns')
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_events_run_id'))

    op.drop_table('run_events')
    with op.batch_alter_table('proposed_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposed_rules_run_id'))

    op.drop_table('proposed_rules')
    with op.batch_alter_table('match_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_pairs_run_id'))

    op.drop_table('match_pairs')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_run_id'))

    op.drop_table('findings')
    op.drop_table('uploads')
    op.drop_table('settings')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_period'))

    op.drop_table('runs')
    op.drop_table('rules')
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_versions_rule_id'))

    op.drop_table('rule_versions')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_run_id'))

    op.drop_table('reports')
    op.drop_table('detectors')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_log_target'))
        batch_op.drop_index(batch_op.f('ix_audit_log_run_id'))

    op.drop_table('audit_log')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
